server.port: 9090
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: "org.hibernate.dialect.MySQL5Dialect"
    hibernate:
      dialect: "org.hibernate.dialect.MySQL5Dialect"
      ddl-auto: create
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/persondb"
    username: root
    password: example
    hikari:
      connectionTimeout: 3000
      idleTimeout: 6000
      maxLifetime: 1800
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: ConnPool
  security:
    ignored: "/**"
    user:
      name: root
      password: root
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "karate"
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
management:
  security:
    ignored: /**
  endpoints:
    web:
      exposure:
        include: "*"
    security:
      ignored: /**
security:
  ignored: /**
